### ISSUE TITLE
#IBMD_BV1_022-Manejo de csv

### ISSUE THREAD

**Issue by ArielAndres7** [AV1R/IBM-Project-Bravo#8]
Negocio: como usuario del IBM Dashboard, me gustaría poder subir mis archivos .csv a la aplicación para obtener la información que desee en mi dashboard.

Técnico:
Agregar la capacidad de importar archivos csv y cargar la información que contienen a la base de datos. Esta información debe poder visualizarse en el dashboard del usuario.

Criterios de Aceptación:

El usuario puede cargar archivos csv a la aplicación.

La información se agrega a la base de datos.

**Comment by MaxvG115** [comment]
Completed on the 30th of May 2023
